#!/usr/bin/env python3
"""
embed_webapp.py - gzip the web app into a PROGMEM C header the firmware serves over
WiFi (GET /  ->  the gzipped app).  Output: <sketch>/webapp_html.h.

Single source of truth: App/www/index.html - the very same file the Android APK is
built from.  There is no separate standalone HTML any more; this script derives the
dongle-served copy from index.html in one step:

  1. Strip the APK-only native BLE bridge (the ble-shim.js <script> + its comment).
     An in-browser / dongle-served copy talks to the browser's own Web Bluetooth (or,
     here, plain HTTP), so it doesn't need - and shouldn't 404 on - ble-shim.js.
  2. Flip FORCE_HTTP on, so the dongle-served copy is HTTP-only (never grabs Bluetooth,
     which would shut the WiFi AP down) and auto-connects with no button.

Run it whenever you change App/www/index.html, BEFORE compiling the firmware:

    python embed_webapp.py

It locates App/www/index.html and the sketch folder (the one containing web_server.cpp)
by searching upward from this script, so it works in the repository layout.
"""
import os, io, re, gzip, hashlib


def find_up(start, relpath):
    """Return the first existing <ancestor>/<relpath> at or above `start`."""
    d = start
    while True:
        p = os.path.join(d, relpath)
        if os.path.exists(p):
            return p
        parent = os.path.dirname(d)
        if parent == d:
            return None
        d = parent


HERE = os.path.dirname(os.path.abspath(__file__))

SRC = find_up(HERE, os.path.join('App', 'www', 'index.html'))
if not SRC:
    raise SystemExit('embed_webapp: could not find App/www/index.html above ' + HERE)

marker = find_up(HERE, os.path.join('Td5_Diagnostic', 'web_server.cpp'))
if not marker:
    raise SystemExit('embed_webapp: could not find the sketch (Td5_Diagnostic/web_server.cpp) above ' + HERE)
OUT = os.path.join(os.path.dirname(marker), 'webapp_html.h')

with open(SRC, 'rb') as f:
    data = f.read()

# Normalise line endings to LF so the output is identical no matter how git checked the
# file out (autocrlf), keeping webapp_html.h byte-stable across machines.
data = data.replace(b'\r\n', b'\n')

# 1) Strip the APK-only native BLE bridge (its comment block + the <script> tag).
REPLACEMENT = (b'<!-- Standalone browser build: talks straight to the Web Bluetooth API. The\n'
               b'     native ble-shim.js bridge is only needed inside the Capacitor APK. -->')
stripped = re.sub(rb'<!--\s*Native BLE bridge[\s\S]*?-->\s*<script src="ble-shim\.js"></script>',
                  lambda m: REPLACEMENT, data, count=1)
if stripped == data:  # fall back to just the tag if the comment ever changes
    stripped = data.replace(b'<script src="ble-shim.js"></script>', REPLACEMENT, 1)
if stripped == data:
    raise SystemExit('embed_webapp: could not find the ble-shim.js bridge to strip from ' + SRC)
data = stripped

# 2) Flip FORCE_HTTP so the dongle-served copy is HTTP-only and auto-connects.
MARK = b'let FORCE_HTTP=false;'
if data.count(MARK) != 1:
    raise SystemExit('embed_webapp: expected exactly one "%s" marker, found %d'
                     % (MARK.decode(), data.count(MARK)))
data = data.replace(MARK, b'let FORCE_HTTP=true;')

# Fixed mtime=0 so the output is reproducible (diff-stable) across runs.
buf = io.BytesIO()
with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=9, mtime=0) as gz:
    gz.write(data)
gzipped = buf.getvalue()

sha = hashlib.sha256(data).hexdigest()[:12]

lines = [
    '// AUTO-GENERATED by tools/embed_webapp.py - DO NOT EDIT.',
    '// Source: App/www/index.html (ble-shim stripped)  sha256:%s  raw=%d gz=%d bytes' % (sha, len(data), len(gzipped)),
    '#ifndef TD5_WEBAPP_HTML_H',
    '#define TD5_WEBAPP_HTML_H',
    '#include <pgmspace.h>',
    '',
    'const uint8_t WEBAPP_HTML_GZ[] PROGMEM = {',
]
for i in range(0, len(gzipped), 16):
    lines.append('  ' + ','.join('0x%02x' % b for b in gzipped[i:i + 16]) + ',')
lines += [
    '};',
    'const size_t WEBAPP_HTML_GZ_LEN = %d;' % len(gzipped),
    '',
    '#endif // TD5_WEBAPP_HTML_H',
]

with open(OUT, 'w', newline='\n') as f:
    f.write('\n'.join(lines) + '\n')

print('embedded  raw=%d  gz=%d bytes  (%.1f%%)  sha=%s' %
      (len(data), len(gzipped), 100.0 * len(gzipped) / len(data), sha))
print('source :', os.path.relpath(SRC))
print('wrote  :', os.path.relpath(OUT))
