#!/usr/bin/env python3
"""
embed_webapp.py - gzip the single-file web app into a PROGMEM C header the firmware
serves over WiFi (GET /  ->  the gzipped app).

Run this whenever you change Td5-Diagnostic.html, BEFORE compiling the firmware:

    python embed_webapp.py

It locates Td5-Diagnostic.html (searching upward from this script) and the sketch
folder (the one containing web_server.cpp), so it works both in the development
tree and in the repository layout. Output: <sketch>/webapp_html.h.
"""
import os, io, gzip, hashlib


def find_up(start, name):
    d = start
    while True:
        p = os.path.join(d, name)
        if os.path.exists(p):
            return p
        parent = os.path.dirname(d)
        if parent == d:
            return None
        d = parent


HERE = os.path.dirname(os.path.abspath(__file__))

SRC = find_up(HERE, 'Td5-Diagnostic.html')
if not SRC:
    raise SystemExit('embed_webapp: could not find Td5-Diagnostic.html above ' + HERE)
ROOT = os.path.dirname(SRC)

# The sketch dir is a sibling (dev tree) or under Firmware/ (repo layout).
CANDIDATES = [
    os.path.join(ROOT, 'Td5_Diagnostic'),
    os.path.join(ROOT, 'Firmware', 'Td5_Diagnostic'),
]
sketch = next((c for c in CANDIDATES if os.path.isfile(os.path.join(c, 'web_server.cpp'))), None)
if not sketch:
    raise SystemExit('embed_webapp: could not find the sketch (web_server.cpp) near ' + ROOT)
OUT = os.path.join(sketch, 'webapp_html.h')

with open(SRC, 'rb') as f:
    data = f.read()

# The dongle-served copy is HTTP-only: flip FORCE_HTTP so it never tries Bluetooth
# (which would grab the session and shut the WiFi AP down) and auto-connects.
MARK = b'let FORCE_HTTP=false;'
if data.count(MARK) != 1:
    raise SystemExit('embed_webapp: expected exactly one "%s" marker, found %d'
                     % (MARK.decode(), data.count(MARK)))
data = data.replace(MARK, b'let FORCE_HTTP=true;')

# Fixed mtime=0 so the output is reproducible (diff-stable) across runs.
buf = io.BytesIO()
with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=9, mtime=0) as gz:
    gz.write(data)
gzipped = buf.getvalue()

sha = hashlib.sha256(data).hexdigest()[:12]

lines = [
    '// AUTO-GENERATED by tools/embed_webapp.py - DO NOT EDIT.',
    '// Source: Td5-Diagnostic.html  sha256:%s  raw=%d gz=%d bytes' % (sha, len(data), len(gzipped)),
    '#ifndef TD5_WEBAPP_HTML_H',
    '#define TD5_WEBAPP_HTML_H',
    '#include <pgmspace.h>',
    '',
    'const uint8_t WEBAPP_HTML_GZ[] PROGMEM = {',
]
for i in range(0, len(gzipped), 16):
    lines.append('  ' + ','.join('0x%02x' % b for b in gzipped[i:i + 16]) + ',')
lines += [
    '};',
    'const size_t WEBAPP_HTML_GZ_LEN = %d;' % len(gzipped),
    '',
    '#endif // TD5_WEBAPP_HTML_H',
]

with open(OUT, 'w', newline='\n') as f:
    f.write('\n'.join(lines) + '\n')

print('embedded  raw=%d  gz=%d bytes  (%.1f%%)  sha=%s' %
      (len(data), len(gzipped), 100.0 * len(gzipped) / len(data), sha))
print('source :', os.path.relpath(SRC))
print('wrote  :', os.path.relpath(OUT))
